CREATE TABLE objectives (id INTEGER PRIMARY KEY, task TEXT, status TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE alerts (id INTEGER PRIMARY KEY, alert_text TEXT, severity TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE action_log (id INTEGER PRIMARY KEY, actor TEXT, action TEXT, details TEXT, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP);
